// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRebzseWIbrAKQYkdbDYpHnRFAMcR6JA',
    appId: '1:307354390878:web:e953b1c4f8279e4dbabfcf',
    messagingSenderId: '307354390878',
    projectId: 'jokers-store',
    authDomain: 'jokers-store.firebaseapp.com',
    storageBucket: 'jokers-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_tgWPnihc74Gxyb7Je0bo1GwZSmORVU',
    appId: '1:307354390878:android:1f7145633a3c9451babfcf',
    messagingSenderId: '307354390878',
    projectId: 'jokers-store',
    storageBucket: 'jokers-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhiRgu3E0x4jTl6FRXn-HZrWVC0kGX6o',
    appId: '1:307354390878:ios:2de9d8801997c812babfcf',
    messagingSenderId: '307354390878',
    projectId: 'jokers-store',
    storageBucket: 'jokers-store.appspot.com',
    androidClientId: '307354390878-m18rt0c3pv7ifi7nq4fi2mj8rjf7h166.apps.googleusercontent.com',
    iosClientId: '307354390878-e0m05vqt6hneak91mc5puk53v3ti4srp.apps.googleusercontent.com',
    iosBundleId: 'com.example.newEcommerceApp',
  );
}
